services:
  postgres:
    image: postgres:15
    container_name: urlshortener-postgres
    environment:
      POSTGRES_USER: urluser
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: urlshortener_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL" , "pg_isready -U urluser"]
      interval: 10s
      timeout: 5s
      retries: 2

  redis:
    image: redis:7
    container_name: urlshortener-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD" , "redis-cli","ping" ]
      interval: 10s
      timeout: 5s
      retries: 2
volumes:
  pgdata: