spring:
  application:
    name: RateLimitedURLShortener
  datasource:
    url: jdbc:postgresql://localhost:5432/urlshortener_dev
    driver-class-name: org.postgresql.Driver
    username: urluser
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

redis:
  host: localhost
  port: 6379

app:
  domain: http://localhost:8080
